# Generated by Django 4.0.6 on 2025-02-03 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the department name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the department', null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor'), ('Vocational', 'Vocational')], help_text='Select the subtype', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Course SubType',
                'verbose_name_plural': 'Course SubTypes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the type', null=True)),
            ],
            options={
                'verbose_name': 'Department Type',
                'verbose_name_plural': 'Department Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the course name', max_length=200, unique=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in years', null=True)),
                ('credits', models.IntegerField(blank=True, help_text='Number of credits', null=True)),
                ('prerequisites', models.TextField(blank=True, help_text='Prerequisites for the course', null=True)),
                ('syllabus_link', models.URLField(blank=True, help_text='URL to the syllabus', null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='department.department')),
                ('subtype', models.ForeignKey(blank=True, help_text='Specify if the course is Major, Minor, or Vocational', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='department.subtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='department.type')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
    ]
