# Generated by Django 4.2.17 on 2025-01-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='post',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
