# Generated by Django 4.0.6 on 2025-02-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
    ]
