# Generated by Django 4.0.6 on 2025-02-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_course_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
