# Generated by Django 4.0.6 on 2025-02-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_subtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.subtype'),
        ),
    ]
