# Generated by Django 4.0.6 on 2025-02-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('submission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_marks', models.IntegerField()),
                ('description', models.TextField()),
                ('late_submission_policy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('cultural', 'Cultural'), ('academic', 'Academic'), ('other', 'Other')], max_length=50)),
                ('audience_type', models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('administrators', 'Administrators'), ('all', 'All')], max_length=50)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('feedback_form', models.URLField(blank=True, null=True)),
                ('live_stream_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_to', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('attachment_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
