# Generated by Django 4.0.6 on 2025-01-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taksdata', '0002_alter_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='submission_format',
        ),
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
