# Generated by Django 4.0.6 on 2025-02-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('taksdata', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='minor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.minor'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vocational',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.vocational'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.course'),
        ),
    ]
