# Generated by Django 4.0.6 on 2025-02-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=20)),
                ('group_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_description', models.TextField(blank=True, null=True)),
                ('group_type', models.CharField(choices=[('official', 'Official'), ('unofficial', 'Unofficial')], default='official', max_length=20)),
                ('wapp_qr', models.ImageField(blank=True, null=True, upload_to='WHATAPP/wapp_qr')),
                ('wapp_logo', models.ImageField(blank=True, null=True, upload_to='WHATAPP/wapp_logo')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.course')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('programe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.programe')),
            ],
        ),
    ]
