# Generated by Django 4.0.6 on 2025-02-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_category',
            field=models.CharField(choices=[('---', '---'), ('minor', 'Minor'), ('major', 'Major'), ('vocational', 'Vocational')], default='---', max_length=20),
        ),
    ]
