# Generated by Django 4.0.6 on 2025-01-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_auto_20250114_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='wapp_logo',
            field=models.ImageField(blank=True, null=True, upload_to='WHATAPP/wapp_logo'),
        ),
        migrations.AddField(
            model_name='group',
            name='wapp_qr',
            field=models.ImageField(blank=True, null=True, upload_to='WHATAPP/wapp_qr'),
        ),
    ]
