# Generated by Django 4.0.6 on 2025-01-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_user_alter_teacher_user'),
        ('whatsapp', '0003_group_wapp_logo_group_wapp_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
